language: python
python: "3.9"
install: pip install Sphinx
script:
  - cd docs
  - make html
  - cd $TRAVIS_BUILD_DIR
deploy:
  - provider: pages
    local-dir: docs/_build/html
    github-token: $GH_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
notifications:
  email: false
